### ISSUE TITLE
Special characters in OpenStudio model make PAT sim fail

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-PAT#84]
See: https://unmethours.com/question/31663/issue-in-parametric-analysis-tool-initial-capital-costs-associated-with-the-improvements-are-0/?comment=31696#post-id-31696

Basically the user's model has special characters in materials such as `Double pane with ½” air space R=2.04`

Running the model with the OpenStudio Results measure enabled make the simulation fail: the E+ runs succesfully, but there's an ASCII to UTF8 problem in the reporting. 
It works just fine in the OpenStudio Application though!

Error log

```
[15:44:29.401331 DEBUG] Passing measure OpenStudioResults of type ModelMeasure
[15:44:29.401359 INFO] Finished applying OpenStudio measures.
[15:44:29.401369 DEBUG] Communicating measure output attributes to the output adapter
[15:44:33.570363 ERROR] Found error in state 'os_measures' with message ["\"\\xE2\" from ASCII-8BIT to UTF-8:/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:81:in `write'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:81:in `<<'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:81:in `block in save_osm'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:81:in `open'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/model.rb:81:in `save_osm'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_os_measures.rb:60:in `perform'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:176:in `block in perform'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:170:in `open'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:170:in `perform'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/performable_method.rb:26:in `perform'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'\n/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'\n/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `call'\n/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/timeout.rb:98:in `timeout'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'\n/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'\n/usr/share/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/command.rb:137:in `run'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/command.rb:125:in `block in run_process'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/application.rb:270:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/application.rb:270:in `block in start_proc'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/application.rb:279:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/application.rb:279:in `start_proc'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/application.rb:300:in `start'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/controller.rb:59:in `run'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons.rb:197:in `block in run_proc'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/cmdline.rb:92:in `call'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons/cmdline.rb:92:in `catch_exceptions'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/daemons-1.2.6/lib/daemons.rb:196:in `run_proc'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/command.rb:123:in `run_process'\n/home/julien/Software/Others/OpenStudio-PAT/depend/OpenStudio-server/gems/gems/delayed_job-4.1.5/lib/delayed/command.rb:98:in `daemonize'\nbin/delayed_job:6:in `<main>'"]}
```

**Comment by jmarrec** [comment]
Similar to https://github.com/NREL/OpenStudio/issues/2671 where I had found out that having an IDF with special characters in comments made it crash, and given this unmet hours question from 8 hours ago, seems it's still the case today: https://unmethours.com/question/32212/measure-and-idf-run-successfully-in-openstudio-but-not-pat/?answer=32218#post-id-32218
